### ISSUE TITLE
host flutter web locally from mobile

### ISSUE THREAD

**Issue by rohitsangwan01** [lesnitsky/flutter_local_assets_server#11]
Hey , can we host our flutter web App by this plugin from Android , so that we can start a local server from mobile , and devices under my wifi can open that hosted flutter web app ?? 
basically whole idea is to share mobiles videos and photos by using local server , and flutter web for a userInterface of transferring data

**Comment by lesnitsky** [comment]
I think this is possible

**Comment by rohitsangwan01** [comment]
@lesnitsky can you share a demo or peace of code

**Comment by nasirdavinci** [comment]
you should have chceked out the closed issue first 

if you wish to serve with local file like download folder then you should use shelf_virtual_directory
