### ISSUE TITLE
Web Page not available

### ISSUE THREAD

**Issue by rupamking1** [lesnitsky/flutter_local_assets_server#3]
Please Help me-

![IMG_20200706_012511](https://user-images.githubusercontent.com/57300218/86541103-ca7c6080-bf27-11ea-9f26-3a93b9ca0348.jpg)

First Error-
Launching lib\main.dart on Redmi Note 7 in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                10.1s
W/Looper  ( 2110): Slow Looper main: Activity com.example.web_test/.MainActivity is 2121ms late (wall=2470ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 1 msg, msg 1 took 2217ms (late=1ms h=android.app.ActivityThread$H w=110)
I/OpenGLRenderer( 2110): Initialized EGL, version 1.4
D/OpenGLRenderer( 2110): Swap behavior 2
Connecting to VM Service at ws://127.0.0.1:61689/esN3ST4Q62g=/ws
I/xample.web_tes( 2110): ProcessProfilingInfo new_methods=519 is saved saved_to_disk=1 resolve_classes_delay=8000
W/xample.web_tes( 2110): Verification of void io.flutter.plugin.platform.VirtualDisplayController.<init>(android.content.Context, io.flutter.plugin.platform.AccessibilityEventsDelegate, android.hardware.display.VirtualDisplay, io.flutter.plugin.platform.PlatformViewFactory, android.view.Surface, io.flutter.view.TextureRegistry$SurfaceTextureEntry, android.view.View$OnFocusChangeListener, int, java.lang.Object) took 117.399ms
I/WebViewFactory( 2110): Loading com.android.chrome version 83.0.4103.106 (code 410410673)
W/xample.web_tes( 2110): Verification of void mn.<init>(android.webkit.WebViewDelegate) took 106.393ms
I/xample.web_tes( 2110): Background concurrent copying GC freed 16067(928KB) AllocSpace objects, 2(40KB) LOS objects, 49% free, 2MB/4MB, paused 2.659ms total 135.141ms
I/cr_LibraryLoader( 2110): Loaded native library version number "83.0.4103.106"
I/cr_CachingUmaRecorder( 2110): Flushed 3 samples from 3 histograms.
W/xample.web_tes( 2110): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/xample.web_tes( 2110): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
W/chromium( 2110): [WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
D/EgretLoader( 2110): EgretLoader(Context context)
D/EgretLoader( 2110): The context is not activity
W/xample.web_tes( 2110): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (light greylist, reflection)
W/cr_media( 2110): Requires BLUETOOTH permission
W/ContentCatcher( 2110): Failed to notify a WebView
W/VideoCapabilities( 2110): Unsupported mime video/divx
W/VideoCapabilities( 2110): Unsupported mime video/divx311
W/VideoCapabilities( 2110): Unsupported mime video/divx4
W/VideoCapabilities( 2110): Unrecognized profile 4 for video/hevc
W/VideoCapabilities( 2110): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 2110): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities( 2110): Unsupported profile 4 for video/mp4v-es
W/Utils   ( 2110): could not parse long range '175-174'
D/NetworkSecurityConfig( 2110): No Network Security Config specified, using platform default
W/Looper  ( 2110): Slow Looper main: doFrame is 391ms late because of 6 msg, msg 1 took 318ms (late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)

Second Error-
W/ContentCatcher(29962): Failed to notify a WebView
E/chromium(29962): [ERROR:aw_browser_terminator.cc(125)] Renderer process (30308) crash detected (code -1).
Restarted application in 1,886ms.
D/EgretLoader(29962): EgretLoader(Context context)
D/EgretLoader(29962): The context is not activity
W/ContentCatcher(29962): Failed to notify a WebView
W/System  (29962): A resource failed to call release.
W/Looper  (29962): Slow Looper main: Activity com.example.web_test/.MainActivity is 353ms late (wall=369ms running=0ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 2 msg, msg 1 took 253ms (late=2ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)

Help me to solve this

**Comment by lesnitsky** [comment]
https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https
